// Generated by `bun init`

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.css" {}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}

interface ImportMetaEnv {
  readonly BUN_PUBLIC_SUPABASE_URL: string;
  readonly BUN_PUBLIC_SUPABASE_PUBLISHABLE_KEY: string;
  readonly BUN_PUBLIC_BACKEND_URL: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
